version: "3"

services:
    nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    depends_on: 
      - api
      - client

    api:
      build:
        dockerilfe: Dockerfile
        context: ./server

    client:
      build:
        dockerfile: Dockerfile
        context: ./client
      depends_on:
        - api